export default {
  // 更换主题
  THEME_CHANGE: 'THEME_CHANGE',
  // 初始化主题
  THEME_INIT: 'THEME_INIT',
  // 下拉刷新
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  // 下拉刷新成功
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  // 下拉刷新失败
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  // 加载更多成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  // 加载更多失败
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',

  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
};
